NUM_STEPS = 9
MAX_LEDS_PER_STEP = 48
STEPS_PER_CONTROLLER = 3

MQTT_HOST = 'localhost'
MQTT_PORT = 1883
MQTT_TOPIC = 'StaIRwaY/'
MQTT_TOPIC_LED = MQTT_TOPIC + 'led/'
MQTT_TOPIC_COLOR = 'color'
MQTT_TOPIC_BARRIER = MQTT_TOPIC + 'barrier/%d/status'
MQTT_TOPIC_STANDALONE = MQTT_TOPIC + 'standalone'

CAN_DEVICE = 'can0'
CAN_BASE_ID = 0x13390000
CAN_BASE_MASK = 0x1FFF0000
CAN_FUNCTION_MASK = 0x1FFF00FF

CAN_ID_HEARTBEAT = 0
CAN_ID_GET_BARRIER_STATUS = 1
CAN_ID_BARRIER_STATUS = 2
CAN_ID_SET_LED = 3
CAN_ID_SET_ALL_LEDS = 4
CAN_ID_UPDATE_LEDS = 5
CAN_ID_SET_DEVICE_CONFIG = 6

COLOR_BLACK = 0x000000
COLOR_RED = 0xFF0000
COLOR_GREEN = 0x00FF00
COLOR_BLUE = 0x0000FF
COLOR_YELLOW = 0xFFFF00
